[tox]
minversion = 4.0
envlist = py312-molecule-docker, py312-molecule-podman
skipsdist = true

[testenv:py312-molecule-docker]
deps =
    ansible-core>=2.14
    molecule>=25.0
    molecule-plugins[docker]
    pytest-testinfra
commands =
    molecule test -s default

[testenv:py312-molecule-podman]
deps =
    ansible-core>=2.14
    molecule>=25.0
    molecule-plugins[podman]
    pytest-testinfra
commands =
    molecule test -s podman
